# Generated by Django 2.2.3 on 2019-07-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.SlugField(unique=True),
        ),
    ]
